--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#08011a"
foreground="#f5f5f5"
cursor="#15c3e9"

-- Colors
color0="#2e2e2e"
color1="#f706cf"
color2="#15c3e9"
color3="#b676b1"
color4="#955ae7"
color5="#4ee2ec"
color6="#7c4dff"
color7="#fccdf5"
color8="#6200ea"
color9="#2a9292"
color10="#00bcd4"
color11="#536dfe"
color12="#105f9c"
color13="#00838f"
color14="#ff3864"
color15="#e4cdfc"
